### ISSUE TITLE
Support for Fargate

### ISSUE THREAD

**Issue by 84nm** [okzk/mackerel-metrics-collect-agent#1]
In the case of Fargate, s3cmd does not support STS and becomes a startup error.

```
ERROR: /root/.s3cfg: Invalid argument
ERROR: Configuration file not available.
ERROR: Consider using --configure parameter to create one.
```

https://github.com/s3tools/s3cmd/issues/546

**Comment by okzk** [comment]
I'm sorry not respond for a long time.

I replaced s3cmd, and tested on Fargate.

**Comment by 84nm** [comment]
Thank you for your response!
